env:
  global:
    - commonPathPomFile: $TRAVIS_BUILD_DIR/common
    - commonBbuildFileName: common-1.0-SNAPSHOT.jar
sudo: required
language: java
jdk:
    - oraclejdk8
before_install:
  - mkdir .travis-github
  - git clone https://github.com/toutfic/travis.git .travis-github
  - chmod +x .travis/deploy.sh
script:
  - mvn clean install -DskipTests
  - .travis/deploy.sh ; artifactory_deploy $commonPathPomFile $commonBbuildFileName
