env:
  global:
    - commonPathPomFile: $TRAVIS_BUILD_DIR/common
    - commonBbuildFileName: common-1.0-SNAPSHOT.jar
sudo: required
language: java
jdk:
    - oraclejdk8
before_install:
  - mkdir .travis
  - git clone https://github.com/toutfic/travis.git .travis
  - chmod +x .travis/scripts/script_init.sh
script:
  - mvn clean install -DskipTests
  - .travis/scripts/script_init.sh .travis/scripts
  - echo $SCRIPT_BASE_DIR
  - artifactory_deploy $commonPathPomFile $commonBbuildFileName
  - artifactory_deploy $commonPathPomFile $commonBbuildFileName

