env:
  global:
    - commonPathPomFile: $TRAVIS_BUILD_DIR/common
    - commonBbuildFileName: common-1.0-SNAPSHOT.jar
sudo: required
language: java
jdk:
    - oraclejdk8
#before_install:

script:
  - mvn clean install -DskipTests
  - mkdir .travis
  - git clone https://github.com/toutfic/travis.git .travis
  - chmod +x .travis/scripts/script_init.sh
  - .travis/scripts/script_init.sh .travis/scripts
  #- artifactory_deploy $commonPathPomFile $commonBbuildFileName
  #- artifactory_deploy $commonPathPomFile $commonBbuildFileName

