env:
  global:
    - SCRIPT_BASE_DIR: $TRAVIS_BUILD_DIR/.travis-github  # Definir le lieu de stockage des script travis (obligatoire)
sudo: required
language: java
jdk:
    - oraclejdk8
addons:
  sonarcloud:
    organization: "calinfo-nc"
    token:
      secure: $SONARQUBE_TOKEN
before_install:
  - mkdir $SCRIPT_BASE_DIR
  - git clone https://github.com/CALINFO-NC/travis.git $SCRIPT_BASE_DIR
  - cp $SCRIPT_BASE_DIR/.m2/settings.xml $HOME/.m2/settings.xml
  - chmod +x .travis/deploy.sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - .travis/deploy.sh
