language: java
jdk:
    - oraclejdk8
script: 
    - mvn clean install
    - curl -H "Authorization: Bearer AKCp2UNCd6WBGDfvtbdfy1Xs3BEbp6DqDFc1CqVFcbaZ2agMxjynwwCgyZSXhnSxyVdjnZGXJ" -X PUT "http://calinfo.jfrog.io/calinfo/my-repository/com/calinfo-nc/services/common.jar" -T /home/travis/build/toutfic/services-common-project/common/target/common.jar
    
    