env:
  global:
    - SCRIPT_BASE_DIR: $TRAVIS_BUILD_DIR/.travis-github  # Definir le lieu de stockage des script travis (obligatoire)
sudo: required
language: java
jdk:
    - oraclejdk8
addons:
  sonarcloud:
    organization: "calinfo-nc"
    token:
      secure: $SONARQUBE_TOKEN
before_install:
  - mkdir $SCRIPT_BASE_DIR
  - git clone https://$TRAVIS_SCRIPT_TOKEN@github.com/CALINFO-NC/travis.git $SCRIPT_BASE_DIR
  - chmod +x $SCRIPT_BASE_DIR/scripts/scripts-init.sh
  - $SCRIPT_BASE_DIR/scripts/scripts-init.sh
  - chmod +x .travis/deploy.sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true sonar:sonar
  - travis_wait 90 .travis/deploy.sh
notifications:
    slack: calinfo-nc:xiw9XrUwovVTx24yk1sgNyO6
