env:
  global:
    - groupId: com.calinfo-nc.services
    - version: 1.0-SNAPSHOT
    - commonArtifactId: common
    - commonPackaging: jar
    - commonPathPomFile: $TRAVIS_BUILD_DIR/common
    - commonBbuildFileName: common-1.0-SNAPSHOT.jar
language: java
jdk:
    - oraclejdk8
before_install:
#  - chmod +x .travis/scripts/artifactory_deploy.sh
  - chmod +x .travis/scripts/test.sh
script:
  - mvn clean install -DskipTests
#  - .travis/scripts/artifactory_deploy.sh $groupId $commonArtifactId $version $commonPackaging $commonPathPomFile $commonBbuildFileName
#  - .travis/scripts/test.sh $groupId $commonArtifactId $version $commonPackaging $commonPathPomFile $commonBbuildFileName
after_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$GITHUB_TOKEN:x-oauth-basic@github.com`n"
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG


