env:
  global:
    - groupId: com.calinfo-nc.services
    - version: 1.0-SNAPSHOT
    - commonArtifactId: common
    - commonPackaging: jar
    - commonPathPomFile: $TRAVIS_BUILD_DIR/common
    - commonBbuildFileName: common-1.0-SNAPSHOT.jar
    
branches:
  except:
    - master
language: java
jdk:
    - oraclejdk8
before_install:
  - chmod +x .travis/scripts/artifactory_deploy.sh
script: 
    - mvn clean install -DskipTests
    - .travis/scripts/artifactory_deploy.sh $groupId $commonArtifactId $version $commonPackaging $commonPathPomFile $commonBbuildFileName
    