env:
  global:
    - groupId: com.calinfo-nc.services
    - version: 1.0-SNAPSHOT
    - commonArtifactId: common
    - commonPackaging: jar
    - commonPathPomFile: $TRAVIS_BUILD_DIR/common
    - commonBbuildFileName: common-1.0-SNAPSHOT.jar
language: java
jdk:
    - oraclejdk8
before_install:
  - mkdir .travis
  - git clone https://github.com/toutfic/travis.git .travis
  - chmod +x .travis/scripts/script_init.sh
  - .travis/scripts/script_init.sh .travis/scripts
script:
  - mvn clean install -DskipTests
#  - .travis/scripts/artifactory_deploy.sh $groupId $commonArtifactId $version $commonPackaging $commonPathPomFile $commonBbuildFileName
#  - .travis/scripts/test.sh $groupId $commonArtifactId $version $commonPackaging $commonPathPomFile $commonBbuildFileName
