env:
  global:
    - SCRIPT_BASE_DIR: $TRAVIS_BUILD_DIR/.travis-github  # Definir le lieu de stockage des script travis (obligatoire)
sudo: required
language: java
jdk:
    - oraclejdk8
before_install:
  - mkdir $SCRIPT_BASE_DIR
  - git clone https://github.com/toutfic/travis.git $SCRIPT_BASE_DIR
  - chmod +x .travis/deploy.sh
script:
  - mvn clean install -DskipTests
  - mvn sonar:sonar -Dsonar.organization=toutfic-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=fb1b3d7d2b6532e6ed7220b94ffe4c90fad2a865
  - .travis/deploy.sh
