common-io:
  storage:
    connector:
      provider: # ce package propose plusieurs provider (google, mem, file)
      configuration: # dépend du provider. pour le provider google, voir la classe GoogleConfigProperties. Pour le provider file voir la classe FileConfigProperties. mem voir MemConfigProperties. etc...

    scheduler:
      enabled: # true pour activer le transfert de donnée binaire
      delay: # Délai en mili seconde entre chaque tentative de transfert