common:
  configuration: # Configuration du common

    domain: # Propriété de la classe DomainProperties

    keycloak: # Propriété de la classe KeycloakProperties

    application: # Propriété de la classe ApplicationProperties

    kafka-event: # Propriété de la classe KafkaProperties
